Rewrite everything
mcbeany-pm-pl/BetterMinion pull request #24
Opened 2022-02-07 13:08 UTC by Mcbeany

## So, what happened to **BetterMinion**

This plugin is expected to be released in March of this year as well as PocketMine 3's EOL. however we are still facing some problems in developing it (specifically we don't know what to do next xD). Besides, I'm quite busy at the moment and want to spend more time studying. We will keep the source code of PM4 and PM3 versions until we finalize this rewritten version.

Release date may be moved to the summer, sorry!

2022-02-12 02:56 UTC, Mcbeany commented
wtf is this type of message :joy:

2022-02-14 01:19 UTC, NgLamVN requested changes

2022-02-14 01:19 UTC, NgLamVN commented on src/minions/entities/BaseMinion.php
> +			$lastItem = $this->minionInventory->getItem($this->minionInventory->getSize() - 1);
This check should be put at another function in MinionInventory like MinionInventory::isFull().

2022-02-14 01:19 UTC, NgLamVN commented on src/minions/entities/BaseMinion.php
> +	public function setNameTag(string $name = "") : void{
$name can be null for empty check, "" still can be a nametag :>

2022-02-14 01:19 UTC, NgLamVN commented on src/minions/entities/BaseMinion.php
> +	public function getWorkingRadius() : int{
Working Radius should put at default value and can be overwrite in other type of the Minion

2022-02-19 10:40 UTC, Mcbeany commented
What's next?
Agh! Farming minion & menu

2022-02-24 09:32 UTC, merged